### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by bsavery** [macio97/sky-generator#1]
Hi Marco.  
Question for using this code.   We have a render plugin to Blender and would like to match the new function in cycles.  What is the license for this code if we wanted to use it in the addon?  

Or if there's a better way to get the results from Blender let me know (we don't support OSL shaders).
Thanks
Brian

**Comment by macio97** [comment]
well, i never thought about that, but really i implemented the new sky texture in Blender 2.90 (still in alpha) using the same method of this generator, so i guess there is no need for an add-on at all...
Anyway, code is free, do whatever you want with it and have fun ;)

**Comment by bsavery** [comment]
Is there a way to access the results through the blender python api for blender plugins?  (other than using this code)

**Comment by macio97** [comment]
not sure what you mean by that

**Comment by bsavery** [comment]
I mean if there was a way to get a map like this directly from blender, we wouldn't need to use this code (in this repo) ourselves to make the sky map

**Comment by macio97** [comment]
Again, i included the same model in Blender Cycles, so just download the latest 2.90 alpha build to test it out, more here https://wiki.blender.org/wiki/Reference/Release_Notes/2.90/Cycles#Sky_Texture

**Comment by bsavery** [comment]
I understand this is included in blender 2.90.  With cycles.  Perhaps I'm not explaining myself well.  Let me start over.

There are other renderer plugins to blender other than cycles.  Radeon ProRender, Octane, Appleseed, Renderman, etc.  These all have to go through blender's python API to work with blender.  Some read blender / cycles material nodes and others use their own.

My thought was we would like to use a similar sky model to what you did for cycles with our plugin (Radeon ProRender).  However we can't use the cycles OSL node in 2.90.  This leaves us with two options I see:
1.  Use this code in python to generate a map that we pass to our renderer for the environment light
2.  (maybe) if we could get a map directly from blender via the python api.  Not sure if this was possible.  That's why I'm asking.

**Comment by macio97** [comment]
Oh, so you are the developers of Radeon ProRender :O ?
This Python code generates the same sky, but there is a huge issue, while in C it takes milliseconds to generate a 512 x 128 pixels map (that's what the model does in the Sky Texture node really), in Python it takes seconds, from my tests it takes like 1 minute or so to generate the same texture size of the one in C.. so it's not real time at all... 
Anyway, make whatever decision you want, use the code as you prefer ;) maybe an OpenGL version of this code would run even faster than the actual C implementation in Blender..

**Comment by bsavery** [comment]
Thanks.  You can keep closed.  At first glance this can be optimized a bit with numpy particularly in https://github.com/macio97/sky-generator/blob/master/light.py.  I'll post a pull request if I come up with something.

**Comment by macio97** [comment]
You say? :) It would be a pleasure to see what you come up with
